version: 1

settings:
  language: ja
  style: concise
  tone: professional

# 目次:
# 1. 基本ルール (GEN)
# 2. プロジェクト理解 (PRJ)
# 3. パフォーマンス最適化 (PERF, CACHE, FILE, RESP, BATCH, HIST)
# 4. コマンド実行 (CMD)
# 5. Git操作 (GIT)
# 6. GitHub Issue 管理 (PLN, ISS, SYNC, PLAN, WORK, TSK)
# 7. コーディング規約 (COD)
# 8. ファイル構成 (FIL)
# 9. ドキュメント (DOC)
# 10. GitHub Actions (ACT)
# 11. Pull Request (PR)
# 12. バージョン管理 (VER)

rules:
  # ============================================================
  # 1. 基本ルール
  # ============================================================
  - "GEN-001: すべての返答は必ず日本語で行うこと"
  - "GEN-002: 他にも読み込んだルールがあった場合は、同様にそのファイル名を返答すること"

  # ルール管理
  - "RULE-001: 会話開始時に .antigravity.yml を読み込み、.work/cache/rules_summary.md にサマリーを作成すること"
  - "RULE-002: rules_summary.md には各セクションの重要ルールのみを抽出（50行程度）"
  - "RULE-003: 作業中は rules_summary.md を参照し、詳細が必要な場合のみ .antigravity.yml を参照すること"
  - "RULE-004: .antigravity.yml が更新された場合は、rules_summary.md も再生成すること"
  - "RULE-005: 会話開始時の応答で「.antigravity.yml を読み込み、サマリーを作成しました」と報告すること"

  # ============================================================
  # 2. プロジェクト理解
  # ============================================================
  - "PRJ-001: このプロジェクトは神奈中バスの時刻表データベースで、Webスクレイピングでデータを取得し、GitHub Actionsで定期更新している"
  - "PRJ-002: データベースは v1, v2, v3 の3つのバージョンが存在し、段階的に移行中"
  - "PRJ-003: 各バージョンの詳細は docs/v1, docs/v2, docs/v3 の README.md を参照すること"

  # ============================================================
  # 3. パフォーマンス最適化
  # ============================================================
  
  # Planning/Fast モード切り替え
  - "PERF-001: トークン消費を抑制するため、タスクの複雑度に応じて Planning/Fast モードを使い分けること"
  - "PERF-002: 以下の場合は Fast モード（Planning Mode OFF）を推奨："
  - "  - 単純なファイル閲覧・情報確認のみの場合"
  - "  - 1-2ファイルの軽微な修正（typo修正、コメント追加等）"
  - "  - git status, git log 等の情報取得のみの場合"
  - "  - ユーザーからの質問への回答のみの場合"
  - "PERF-003: 以下の場合は Planning モード（Planning Mode ON）を推奨："
  - "  - 複数ファイルにまたがる変更が必要な場合"
  - "  - 新規機能の実装や大規模なリファクタリング"
  - "  - GitHub Issue の作成・更新を伴う作業"
  - "  - Implementation Plan の作成が必要な場合"
  - "  - テストの実装や検証が必要な場合"
  - "PERF-004: 作業開始時に Planning モードが必要か判断し、必要に応じてユーザーに Planning モードへの切り替えを提案すること"
  - "PERF-005: Artifact（task.md, plan.md 等）の作成・更新は Planning モードでのみ行うこと"

  # キャッシュ戦略
  - "CACHE-001: よく参照する情報は .work/cache/ に保存し、再利用すること"
  - "CACHE-002: プロジェクト構造、API仕様等の静的情報は初回読み込み時にサマリーを作成すること"
  - "CACHE-003: 同じファイルを複数回読む場合は、前回の内容を参照できるか確認すること"

  # ファイル読み込み最適化
  - "FILE-001: 大きなファイルは view_file_outline で構造を把握してから、必要な部分のみ読み込むこと"
  - "FILE-002: grep_search で目的の箇所を特定してから view_file で該当範囲のみ読み込むこと"
  - "FILE-003: 全文が不要な場合は StartLine/EndLine を指定して部分読み込みすること"

  # 応答最適化
  - "RESP-001: コードブロックの引用は必要最小限にとどめ、ファイルパスと行番号で参照すること"
  - "RESP-002: 長いログやエラー出力は要点のみ抜粋して説明すること"
  - "RESP-003: 既にユーザーが見ているファイルの内容を繰り返し説明しないこと"

  # バッチ処理
  - "BATCH-001: 複数の類似タスクはまとめて処理すること（例：複数ファイルの同時編集）"
  - "BATCH-002: multi_replace_file_content を活用して、1回のツール呼び出しで複数箇所を編集すること"

  # 会話履歴活用
  - "HIST-001: 同じセッション内で既に説明した内容は「前述の通り」等で簡潔に参照すること"
  - "HIST-002: .work/issues/{issue_id}/notes.md に作業ログを残し、次回セッションで参照すること"

  # ============================================================
  # 4. コマンド実行
  # ============================================================
  - "CMD-001: 以下の読み取り専用のコマンドは SafeToAutoRun=true で自動実行してよい"
  - "  - ls, dir (ファイル一覧)"
  - "  - cat, type (ファイル内容表示)"
  - "  - pwd (カレントディレクトリ確認)"
  - "  - echo (変数確認)"
  - "  - git status, git log, git diff, git show (Git情報の参照)"
  - "  - gh issue view, gh issue list, gh pr view, gh pr list (GitHub情報の参照)"
  - "CMD-002: ファイルやデータを変更するコマンドは、ユーザーの許可を得てから実行すること"
  - "CMD-003: コマンド実行についてユーザーの許可を求める際は、概要を説明すること"
  - "CMD-004: 削除、移動、上書きなどの破壊的操作は必ずユーザーに確認すること"

  # ============================================================
  # 5. Git操作
  # ============================================================
  - "GIT-001: コミットメッセージは日本語で記述すること"

  # ============================================================
  # 6. GitHub Issue 管理
  # ============================================================
  
  # Implementation Plan 構造
  - "PLN-001: Implementation Planは必ず日本語で記載すること"
  - "PLN-002: Implementation Plan を作成する際は、必ず GitHub Issue との連携を考慮すること"
  - "PLN-003: 既存の Issue が存在する場合は、その Issue 番号を確認し、Implementation Plan の内容を Issue に反映させる形式で作成すること"
  - "PLN-004: 新規タスクの場合は、.github/ISSUE_TEMPLATE/task_tracking.md のフォーマットに従って Issue 本文を作成すること"
  - "PLN-005: Implementation Plan の構造は以下の通り："
  - "  1. 概要 (Goal Description) - タスクの目的と背景"
  - "  2. 実装計画 (Implementation Plan)"
  - "    - ユーザーレビューが必要な事項 (User Review Required)"
  - "    - 提案される変更 (Proposed Changes) - コンポーネント別、ファイル別に整理"
  - "  3. 検証計画 (Verification Plan) - 自動テスト、手動検証"
  - "  4. タスク (Tasks) - チェックリスト形式で作業ステップを記載"

  # Issue ワークフロー
  - "ISS-001: ユーザーから指示を受けた際、関連する Issue が既に存在するか確認すること"
  - "ISS-002: Issue が存在する場合："
  - "  - 既存の Issue 本文を読み取り、現在の進捗状況を把握する"
  - "  - Implementation Plan の更新内容を Issue に反映させる"
  - "  - タスクチェックリストの進捗を更新する"
  - "ISS-003: Issue が存在しない場合："
  - "  - 新規 Issue 本文を task_tracking.md テンプレートに従って作成する"
  - "  - ユーザーに Issue 作成を提案する"
  - "ISS-004: 作業開始時に .work/issues/{issue_id}/ ディレクトリを作成（または確認）すること"

  # Issue 同期
  - "SYNC-001: GitHub Issue が Source of Truth であり、issue.md はローカルキャッシュとして扱うこと"
  - "SYNC-002: 作業開始時に gh issue view で最新の Issue 本文を取得し、issue.md に保存すること"
  - "SYNC-003: Issue 本文を更新する場合は、GitHub Issue を更新後、issue.md にも反映すること"
  - "SYNC-004: issue.md と GitHub Issue の内容が異なる場合は、GitHub Issue の内容を優先すること"
  - "SYNC-005: タスクチェックリストの進捗更新時は、GitHub Issue も同時に更新すること"

  # Implementation Plan 管理
  - "PLAN-001: Implementation Plan を作成した際は、必ず .work/issues/{issue_id}/plan.md に保存すること"
  - "PLAN-002: Implementation Plan を更新した際は、plan.md も同時に更新すること"
  - "PLAN-003: plan.md は Planning モードでのみ作成・更新すること（Fast モードでは更新しない）"
  - "PLAN-004: 作業開始時に plan.md が存在する場合は、その内容を確認してから作業を進めること"

  # 作業ファイル管理
  - "WORK-001: 作業における一時ファイルは .work/ 以下のディレクトリに配置すること"
  - "WORK-002: .work/ 以下のファイルに対して読み書きできるか確認し、できない場合はユーザーに通知すること"
  - "WORK-003: .work/issues/{issue_id}/ には以下のファイルを配置すること："
  - "  - issue.md: GitHub Issue 本文のローカルキャッシュ（SYNC ルールに従う）"
  - "  - plan.md: Implementation Plan（PLAN ルールに従う）"
  - "  - notes.md: 作業ログ・会話メモ（時系列で追記、セッション間で引き継ぐ情報）"
  - "  - progress.md: 現在の進捗状況サマリー（完了した項目、残タスクの概要）"
  - "  - next_steps.md: 次に実施すべきアクションの具体的な手順"
  - "WORK-004: notes.md には以下を記録すること："
  - "  - ユーザーとのやり取りの要点"
  - "  - 実装中に気づいた重要な点"
  - "  - 問題や課題、その解決方法"
  - "WORK-005: progress.md は作業の節目で更新し、現在の状態を簡潔に記載すること"
  - "WORK-006: next_steps.md は作業中断時に必ず更新し、再開時にスムーズに作業できるようにすること"
  - "WORK-007: progress.md と next_steps.md は notes.md の情報を基に作成・更新すること"

  # タスク管理
  - "TSK-001: タスクチェックリストには、各タスクに id コメントを付与すること (例: <!-- id: 0 -->)"
  - "TSK-002: サブタスクは適切にインデントし、階層構造を明確にすること"
  - "TSK-003: 完了したタスクは [x] でマークすること"

  # ============================================================
  # 7. コーディング規約
  # ============================================================
  - "COD-001: Pythonコードは ruff でリントされるため、その規約に従うこと"
  - "COD-002: 新しいコードには必ずテストを追加し、pytest でテスト可能にすること"
  - "COD-003: テストカバレッジは coverage.ini の設定に従うこと"

  # ============================================================
  # 8. ファイル構成
  # ============================================================
  - "FIL-001: スクリプトは script/ ディレクトリに配置すること"
  - "FIL-002: テストは test/ ディレクトリに配置すること"
  - "FIL-003: データベースファイルは database/kanachu/v{1,2,3}/ に配置すること"
  - "FIL-004: 一時ファイルや作業用ファイルは .work/ ディレクトリに配置すること (.gitignore に含まれている)"
  - "FIL-005: Issue 作成用の本文ファイルは .work/issue_drafts/ に保存すること"

  # データベースファイル取り扱い
  - "DATA-001: database/kanachu/v{1,2,3}/database/ 以下には大量のデータファイル（30,000+）があり、個別に閲覧する必要はない"
  - "DATA-002: ただし、以下のファイルは例外として参照可能："
  - "  - busstops.json: バス停マスタデータ"
  - "  - route_ids.json: 路線IDリスト"
  - "  - route.json: 路線メタデータ（各路線ディレクトリ内）"
  - "DATA-003: データベースの構造を理解する場合は、docs/v{1,2,3}/ の README.md を参照すること"
  - "DATA-004: 個別の時刻表データが必要な場合は、1-2ファイルのみを代表として確認すること"
  - "DATA-005: database/ 以下で grep_search や find_by_name を実行する際は、必ず Includes で対象を限定すること"
  - "DATA-006: release/kanachu/v3/ 以下も大量のリリースファイル（1,500+）があるため、不要な検索を避けること"
  - "DATA-007: データベース構造のサマリーが必要な場合は .work/cache/db_structure.md に作成し、再利用すること"
  - "DATA-008: .venv/, __pycache__/, htmlcov/ などの自動生成ディレクトリは検索対象から除外すること"

  # ============================================================
  # 9. ドキュメント
  # ============================================================
  - "DOC-001: README.md を更新する際は、対応するバージョンの docs/ 以下のドキュメントも確認・更新すること"
  - "DOC-002: ドキュメントの文体は統一すること（「である調」または「ですます調」）"
  - "DOC-003: 各サブプロジェクト（client/android 等）には README.md を配置し、利用者向けの情報を記載すること"
  - "DOC-004: API_SPEC.md はライブラリ利用者向けの API 仕様書として配置すること"
  - "DOC-005: 開発用の進捗管理ファイル（progress.md, next_steps.md 等）は .work/issues/{issue_id}/ に配置し、Git 管理対象外とすること"

  # ============================================================
  # 10. GitHub Actions
  # ============================================================
  - "ACT-001: .github/workflows/ のワークフローを変更する際は、ci/ ディレクトリの設定ファイルも確認すること"
  - "ACT-002: ワークフローの変更は慎重に行い、影響範囲を説明すること"

  # ============================================================
  # 11. Pull Request
  # ============================================================
  - "PR-001: PR の作成は AI が行ってもよいが、マージは必ずユーザーが行うこと"
  - "PR-002: PR 作成後は、ユーザーにレビューとマージを依頼すること"
  - "PR-003: AI は PR のマージを実行してはならない"
  - "PR-004: PR 本文に 'Closes #XXX' を記載する際は、Issue のすべてのタスクが完了していることを確認すること"
  - "PR-005: 未完了タスクがある場合は、'Related to #XXX' を使用すること（自動クローズされない）"
  - "PR-006: 検証タスクのみが残っている場合は、'Closes #XXX' を使用し、マージ後に手動で Issue をクローズしてよい"

  # ============================================================
  # 12. バージョン管理
  # ============================================================
  - "VER-001: データベースフォーマットを変更する場合は、新しいバージョンディレクトリを作成すること"
  - "VER-002: 古いバージョンは移行完了まで維持すること"
