version: 1

settings:
  language: ja
  style: concise
  tone: professional

rules:
  # 基本ルール
  - "GEN-001: 必ず .antigravity.yml を参考にすること"
  - "GEN-002: .antigravity.yml を読み込んだら「.antigravity.yml を読み込みました」と返答すること"
  - "GEN-003: 他にも読み込んだルールがあったら、そのファイル名を返答すること"
  - "GEN-004: すべての返答は必ず日本語で行うこと"

  # コマンド実行
  - "CMD-001: 以下の読み取り専用のコマンドは SafeToAutoRun=true で自動実行してよい"
  - "  - ls, dir (ファイル一覧)"
  - "  - cat, type (ファイル内容表示)"
  - "  - pwd (カレントディレクトリ確認)"
  - "  - echo (変数確認)"
  - "  - git status, git log, git diff, git show (Git情報の参照)"
  - "  - gh issue view, gh issue list, gh pr view, gh pr list (GitHub情報の参照)"
  - "CMD-002: ファイルやデータを変更するコマンドは、ユーザーの許可を得てから実行すること"
  - "CMD-003: 削除、移動、上書きなどの破壊的操作は必ずユーザーに確認すること"

  # Git操作
  - "GIT-001: コミットメッセージは日本語で記述すること"
  
  # プロジェクト理解
  - "PRJ-001: このプロジェクトは神奈中バスの時刻表データベースで、Webスクレイピングでデータを取得し、GitHub Actionsで定期更新している"
  - "PRJ-002: データベースは v1, v2, v3 の3つのバージョンが存在し、段階的に移行中"
  - "PRJ-003: 各バージョンの詳細は docs/v1, docs/v2, docs/v3 の README.md を参照すること"
  
  # Implementation Plan と GitHub Issue の連携
  - "PLN-001: Implementation Planは必ず日本語で記載すること"
  - "PLN-002: Implementation Plan を作成する際は、必ず GitHub Issue との連携を考慮すること"
  - "PLN-003: 既存の Issue が存在する場合は、その Issue 番号を確認し、Implementation Plan の内容を Issue に反映させる形式で作成すること"
  - "PLN-004: 新規タスクの場合は、.github/ISSUE_TEMPLATE/task_tracking.md のフォーマットに従って Issue 本文を作成すること"
  - "PLN-005: Implementation Plan の構造は以下の通り："
  - "  1. 概要 (Goal Description) - タスクの目的と背景"
  - "  2. 実装計画 (Implementation Plan)"
  - "    - ユーザーレビューが必要な事項 (User Review Required)"
  - "    - 提案される変更 (Proposed Changes) - コンポーネント別、ファイル別に整理"
  - "  3. 検証計画 (Verification Plan) - 自動テスト、手動検証"
  - "  4. タスク (Tasks) - チェックリスト形式で作業ステップを記載"
  
  # Issue 更新のワークフロー
  - "ISS-001: ユーザーから指示を受けた際、関連する Issue が既に存在するか確認すること"
  - "ISS-002: Issue が存在する場合："
  - "  - 既存の Issue 本文を読み取り、現在の進捗状況を把握する"
  - "  - Implementation Plan の更新内容を Issue に反映させる"
  - "  - タスクチェックリストの進捗を更新する"
  - "ISS-003: Issue が存在しない場合："
  - "  - 新規 Issue 本文を task_tracking.md テンプレートに従って作成する"
  - "  - ユーザーに Issue 作成を提案する"
  - "ISS-004: 作業開始時に .work/issues/{issue_id}/ ディレクトリを作成（または確認）すること"
  - "ISS-005: Issue の本文は issue.md に保存し、常に最新状態を保つこと"
  - "ISS-006: Implementation Plan は plan.md として保存すること"
  - "ISS-007: ユーザーとのやり取りや作業の進捗は、セッションの終了を待たずに適宜 notes.md に追記し、常に最新の状況がわかるようにすること"
  
  # タスク管理
  - "TSK-001: タスクチェックリストには、各タスクに id コメントを付与すること (例: <!-- id: 0 -->)"
  - "TSK-002: サブタスクは適切にインデントし、階層構造を明確にすること"
  - "TSK-003: 完了したタスクは [x] でマークすること"
  
  # コーディング規約
  - "COD-001: Pythonコードは ruff でリントされるため、その規約に従うこと"
  - "COD-002: 新しいコードには必ずテストを追加し、pytest でテスト可能にすること"
  - "COD-003: テストカバレッジは coverage.ini の設定に従うこと"
  
  # ファイル構成
  - "FIL-001: スクリプトは script/ ディレクトリに配置すること"
  - "FIL-002: テストは test/ ディレクトリに配置すること"
  - "FIL-003: データベースファイルは database/kanachu/v{1,2,3}/ に配置すること"
  - "FIL-004: 一時ファイルや作業用ファイルは .work/ ディレクトリに配置すること (.gitignore に含まれている)"
  - "FIL-005: Issue 作成用の本文ファイルは .work/issue_drafts/ に保存すること"
  
  # ドキュメント
  - "DOC-001: README.md を更新する際は、対応するバージョンの docs/ 以下のドキュメントも確認・更新すること"
  - "DOC-002: ドキュメントの文体は統一すること（「である調」または「ですます調」）"
  
  # GitHub Actions
  - "ACT-001: .github/workflows/ のワークフローを変更する際は、ci/ ディレクトリの設定ファイルも確認すること"
  - "ACT-002: ワークフローの変更は慎重に行い、影響範囲を説明すること"
  
  # Pull Request
  - "PR-001: PR の作成は AI が行ってもよいが、マージは必ずユーザーが行うこと"
  - "PR-002: PR 作成後は、ユーザーにレビューとマージを依頼すること"
  - "PR-003: AI は PR のマージを実行してはならない"
  - "PR-004: PR 本文に 'Closes #XXX' を記載する際は、Issue のすべてのタスクが完了していることを確認すること"
  - "PR-005: 未完了タスクがある場合は、'Related to #XXX' を使用すること（自動クローズされない）"
  - "PR-006: 検証タスクのみが残っている場合は、'Closes #XXX' を使用し、マージ後に手動で Issue をクローズしてよい"
  
  # バージョン管理
  - "VER-001: データベースフォーマットを変更する場合は、新しいバージョンディレクトリを作成すること"
  - "VER-002: 古いバージョンは移行完了まで維持すること"
