:toc: macro
:toclevels: 6
:toc-title: 目次

= BusTimeTableDatabase

image::https://github.com/asabon/BusTimeTableDatabase/actions/workflows/release.yml/badge.svg?branch=main[https://github.com/asabon/BusTimeTableDatabase/actions/workflows/release.yml]

toc::[]

== 概要

* json 形式で作成した、バスの時刻表データベース。
* 手作業での入力のため、自分が必要な部分しか入力してない。

== 目的

* バスの時刻表を扱うアプリから参照できるデータの構築。
* データを public リポジトリで公開することで自分以外の人にもデータ編集できるようにする。

== ディレクトリ構成

=== database/

* データベースを json 形式で管理しているルートディレクトリ。
* この階層では会社を以下のようにディレクトリで管理している。

[source, text]
....
+ [COMPANY]/     : 会社「COMPANY」のディレクトリ(`kanachu` など)
+ companies.json : この階層にある「会社」ディレクトリの説明
....

companies.json の書式は以下。

[source, json]
....
{
    "companies": [
        {
            "name": "神奈川中央交通",
            "directory": "kanachu"
        }
    ]
}
....

* companies
** 以下の要素を会社ごとに配列で持つ。
* name
** 会社名。略称ではなく正式名称とする。
* directory
** ディレクトリ名をこの階層からの相対パスで設定する。

==== COMPANY/

* バスの「系統」をディレクトリで管理している。

[source, text]
....
+ [SYSTEM]/    : 系統「SYSTEM」のディレクトリ(`m12` など)
+ ...
....

===== SYSTEM/

* 同じ「系統」でも行先や経由地点などにより異なるものをディレクトリで管理している。

[source, text]
....
+ [SYSTEM-ROUTE-A] : 区別できれば何でもいい (`to_kiso_minami_danchi` など)
+ ...
....

====== SYSTEM-ROUTE/

* バス停ごとの時刻表を json 形式で管理。
* メンテしやすさを考慮して、経路の順番に 01 → 02 → ... とファイル名を付与している。

[source, text]
....
+ 01_[BUS-STOP-01].json : バス停[BUS-STOP-01]の時刻表データ。
+ route.json            : バス停の名称とファイルを紐づける json。
....

route.json の書式は以下。

[source, json]
....
{
    "system": "町12",
    "destination": "木曽南団地",
    "stations": [
        {
            "name": "町田バスセンター",
            "file": "01_machida_bus_center_2.json"
        },
        // 以下、続く ...
    ]
}
....

* system
** 系統
* destination
** ゴール地点
* stations
** スタート地点からゴール地点まで順に並んでいる。
** 以下の要素を持つ。
*** name
**** 地点の名称。
**** 同じ地点の名称は他のファイルと完全に一致すること。
*** file
**** ファイル名。

各時刻表データ.json の書式は以下。

[source, json]
....
{
  "date": "2024/07/08",
  "name": "町田バスセンター",
  "position": "2番のりば",
  "system": "町12",
  "destinations": [
    "境川団地",
    "木曽南団地"
  ],
  "weekday": [
    "6:55",
    "7:40", "7:52",
    "9:04",
    "21:28",
    "22:20"
  ],
  "saturday": [
  ],
  "holiday": [
  ]
}
....

* date
** 時刻表更新日
* name
** 名称
* position
** 同じ名称の地点でも、異なる位置がある場合、それを識別するための名称を入れる。
** 1番乗り場と2番乗り場、など
* system
** 系統
* destinations
** 削除予定
* weekday
** 平日の時刻表を "HH:MM" 形式の文字列の配列で表現。
* saturday
** 土曜の時刻表を "HH:MM" 形式の文字列の配列で表現。
* holiday
** 休日の時刻表を "HH:MM" 形式の文字列の配列で表現。

=== release/

* リリース物を管理するディレクトリ。
* 以下のファイルが格納されている。
** hash.txt
*** database 以下の json データから生成した hash
*** この値が変わっていたら「データベースが更新された」とみなす
** timetable.zip
*** database 以下を zip で固めたもの
* これらのファイルは main ブランチの database が変更されたときに自動的に更新される。

=== script/

* GitHub Actions から実行される script 群。

== LICENSE

MIT License.
