name: Check database

on:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - '.github/workflows/check_database.yml'
  #    - 'script/check_all.py'
  #    - 'script/check_timetable.py'
  #    - 'database/神奈川中央交通/**/*.json'
  #pull_request:
  #  branches:
  #    - main
  #  paths:
  #    - '.github/workflows/check_database.yml'
  #    - 'script/check_all.py'
  #    - 'script/check_timetable.py'
  #    - 'database/神奈川中央交通/**/*.json'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check database
        run: python script/check_all.py "database/神奈川中央交通"
