name: Generate Timetable

on:
  schedule:
    - cron: '0 0 1 * *' # 毎月1日の00:00に実行
  workflow_dispatch:
    inputs:
      forceUpdate:
        description: 'Force update'
        required: true
        type: boolean
        default: false
      createPullRequest:
        description: 'Create pull request'
        required: true
        type: boolean
        default: true

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set arguments for schedule
        if: github.event_name == 'schedule'
        run: |
          echo "FORCE_UPDATE=false" >> $GITHUB_ENV
          echo "CREATE_PULL_REQUEST=true" >> $GITHUB_ENV

      - name: Set arguments for manual dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "FORCE_UPDATE=${{ github.event.inputs.forceUpdate }}" >> $GITHUB_ENV
          echo "CREATE_PULL_REQUEST=${{ github.event.inputs.createPullRequest }}" >> $GITHUB_ENV

      - name: Generate timetable
        run: python script/generate.py "database/神奈川中央交通" ${{ env.FORCE_UPDATE }}

      - name: Create pull request
        if: env.CREATE_PULL_REQUEST == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update timetable"
          title: "Update timetable"
          body: "Update timetable"
          branch: "feature/update-timetable"
