name: Generate Timetable

on:
    workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate timetable
        run: python script/generate.py "database/神奈川中央交通"

#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#            name: new-timetable
#            path: database/神奈川中央交通/町17_町田バスセンター行_木曽南団地経由_淵野辺駅北口発/11_町田総合高校前.json
