name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'database/**'
      - '.github/workflows/*.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Get old hash
        run: |
          OLD_HASH=$(cat release/hash.txt)
          echo "OLD_HASH=$OLD_HASH" >> $GITHUB_ENV

      - name: Generate new hash
        run: |
          HASH=$(python -c "from script.hash import hash_directory; print(hash_directory('database'))")
          echo "NEW_HASH=$HASH" >> $GITHUB_ENV

      - name: Create release file
        if: env.OLD_HASH != env.NEW_HASH
        run: |
          rm -rf release/
          mkdir release
          zip -r release/timetable.zip database
          echo "${{ env.NEW_HASH }}" > release/hash.txt

      - name: Create pull request
        if: env.OLD_HASH != env.NEW_HASH
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Automated changes"
          title: "Release"
          body: "Release"
          branch: "release"
          add-paths: "release"

      - name: Upload artifact
        if: env.OLD_HASH != env.NEW_HASH
        uses: actions/upload-artifact@v4
        with:
          name: timetable-database
          path: release/
