name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'database/**'
      - '.github/workflows/release.yml'

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Get old hash
        run: |
          OLD_HASH=$(python script/get_hash_from_json.py release/info.json)
          echo "OLD_HASH=$OLD_HASH" >> $GITHUB_ENV
          echo "OLD_HASH=<$OLD_HASH>"

      - name: Generate new hash
        run: |
          NEW_HASH=$(python -c "from script.hash import hash_directory; print(hash_directory('database'))")
          echo "NEW_HASH=$NEW_HASH" >> $GITHUB_ENV
          echo "NEW_HASH=<$NEW_HASH>"

      - name: Create release file
        if: env.OLD_HASH != env.NEW_HASH
        run: |
          rm -rf release/
          mkdir release
          zip -r release/database.zip database
          python script/edit_json.py update release/info.json "hash" "${{ env.NEW_HASH }}"

      - name: Create pull request
        if: env.OLD_HASH != env.NEW_HASH
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Automated changes"
          title: "Release"
          body: "Release"
          branch: "release"
          add-paths: "release"

      - name: Upload artifact
        if: env.OLD_HASH != env.NEW_HASH
        uses: actions/upload-artifact@v4
        with:
          name: timetable-database
          path: release/
