name: Release

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  release:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Create release file
        run: |
          HASH_LEGACY=$(python -c "from script.common.hash import hash_directory; print(hash_directory('database/神奈川中央交通'))")
          mkdir -p release
          rm release/info.json
          rm release/database.zip
          rm database-sql.zip
          zip -r release/database.zip database
          python script/common/edit_json.py update release/info.json "hash" HASH_LEGACY
          python script/json_to_sqlite.py 'database/神奈川中央交通' timetable.db
          zip -r release/database-sql.zip timetable.db

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Automated changes"
          title: "Release"
          body: "Release"
          branch: "release/legacy"
          add-paths: "release"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: timetable-database
          path: release/
