name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Get old hash
        run: |
          OLD_HASH=$(python script/get_hash_from_json.py release/info.json)
          echo "OLD_HASH=$OLD_HASH" >> $GITHUB_ENV
          echo "OLD_HASH=<$OLD_HASH>"

      - name: Generate new hash
        run: |
          NEW_HASH=$(python -c "from script.hash import hash_directory; print(hash_directory('database'))")
          echo "NEW_HASH=$NEW_HASH" >> $GITHUB_ENV
          echo "NEW_HASH=<$NEW_HASH>"

      - name: Create release file
        if: env.OLD_HASH != env.NEW_HASH
        run: |
          rm -rf release/
          mkdir release
          zip -r release/database.zip database
          python script/edit_json.py update release/info.json "hash" "${{ env.NEW_HASH }}"
          python script/json_to_sqlite.py 'database/神奈川中央交通' timetable.db
          zip -r release/database-sql.zip timetable.db

      - name: Release for v1
        run: |
          mkdir release/kanachu/v1
          HASH_V1=$(python -c "from script.hash import hash_directory; print(hash_directory('database/kanachu/v1'))")
          python script/edit_json.py update release/kanachu/v1/info.json "hash" $HASH_V1"
          zip -r release/kanachu/v1/database.zip database/kanachu/v1

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Automated changes"
          title: "Release"
          body: "Release"
          branch: "release"
          add-paths: "release"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: timetable-database
          path: release/
